### ISSUE TITLE
Expérience map 24/12/2018

### ISSUE THREAD

**Issue by lacaux-gerome** [DeathCoinOfTheDoom/h2w#12]
- [x] En fonction du parcours finale établir l'experience map avec les humeurs et les points de frustrations
- [x] Dégager les réponses apportées par notre application

**Comment by JessicaThi** [comment]
![experience-map](https://user-images.githubusercontent.com/22913672/49576752-33fc4d80-f946-11e8-901b-fa60497689fc.jpg)

**Comment by JessicaThi** [comment]
Premier aperçu de l'expérience map

![experience-map](https://user-images.githubusercontent.com/22913672/49576803-4f675880-f946-11e8-8e14-834f07161444.jpg)

**Comment by JessicaThi** [comment]
Correction d'orthographe

![experience-map](https://user-images.githubusercontent.com/22913672/49589063-ada53300-f968-11e8-8f5a-d6402d2603a8.jpg)
