### ISSUE TITLE
MVP 01/12/2018

### ISSUE THREAD

**Issue by monacalibani** [DeathCoinOfTheDoom/h2w#17]
Définir MVP

**Comment by Akecel** [comment]
Due date pour ça c'est le 6/12 du coup @monacalibani  ?

**Comment by lacaux-gerome** [comment]
## MVP 😎: 

**Création d'un compte :** 
- Sign up via numéro de téléphone et code de confirmation

**Création de profil :** 
- Information personnels
- Ajout de documents via photo/scan ou upload (pdf, jpg, png)

**Stockage et gestion de dossier :**  
- Supprimer
- Ajouter  
- Modifier

--------------------------------------

**Le futur :** 
- Organiser les dossiers
- Onboarding 
- Tuto
- Sécurité (crypter)
- Associer une annonce à notre dossier, petit mémo (titre, courte description, date)
- Envois de mail interne à l'application
- Tracking de mail
- Parcours différent pour les clients venant d'un autre pays
- Notification push (rappel compléter son dossier)

**Comment by Akecel** [comment]
Connexion par téléphone ? Ca change mes plans ça x)
