### ISSUE TITLE
Questionnaire Physique 20/11/2018

### ISSUE THREAD

**Issue by monacalibani** [DeathCoinOfTheDoom/h2w#18]
Définir les questions à poser lors des entretiens physiques d'étudiants ou d'agents immobilier

- [x] Questions pour les étudiants

**Comment by lacaux-gerome** [comment]
### Étudiant :

Impression globale sur la facilité de trouver un bien ?   Impression globale sur le process - les documents nécessaire

Quel était le plus gros problème pour réunir tes papier ?

Garde tu tes papiers au même endroit (où)? 


### Pas locataire :

Pour quel raison (en gros ou vis tu) ?

Quel serait tes peurs global au fait de prendre un appart.

Quel sont tes peurs administratives ?

Par quel moyen passerai tu afin de te renseigner sur les papiers nécessaires ? 


### Suite pour tous

Passerai tu par une application qui t’accompagnerai à crée ton dossier ?

Virtualises tu tes documents ? - > Comment ?

Utilises-tu des plateforme comme dropbox, google drive pour stocker des documents perso ? 

Es tu familier avec les démarches administratives ? (n'importe quel démarche)

Quels ont été les problèmes que tu as rencontré ?

**Comment by Akecel** [comment]
@lacaux-gerome 

Dans la virtualisation il faudrait ajouter une nuance, c'est assez large, es ce qu'on parle d'un vrai virtualisation ou es ce qu'on demande si il garde tout ces papier en virtuel quelque part (drive etc ) 
Si par exemple on se rend compte qu'énormement de gens utilise drive ou un cloud pour stocker leur parpier administratif, on peut noter ça dans le backlog 

On pourrais aussi ajouter une précision pourquoi à : 
Passerai tu par une application qui t’accompagnerai à crée ton dossier ?

On pourrait demander pourquoi oui, on pourrais cerner encore mieux certain besoin grâce à la réponse, on pourrait aussi demander pourquoi non et voir si il y des inquiétude niveau sécurité ou perte etc et basé affiné les fonctionnalité et/ou la com pour essayer de régler ça

Pour finir je rajouterai bien une question quant à l’habitude administrative, essayé de voir si les étudiant on l'habitude de l'administratif, même en dehors du logement (entreprenariat etc)

Sinon les questions me paraissent pertinente et ça me parrait bon pour ça en tout cas. 

J'ai pas encore check le form mais si y'a des ressemblance mes remarque sont bonne aussi pour ça

**Comment by Akecel** [comment]
- Es tu locataire ?

 OUI : 
- Que pense tu du fait de trouver un bien  Simple ou pas ?
- Que pense tu du process, de tout ce qu'il y a besoin etc ?
- Si tu as déjà constituer un dossier pour un appartement quel était le plus gros problème pour réunir tes papier ? Si non quesqu'y te ferai le plus peur d'après toi ?
- Garde tu tes papiers au même endroit ? Si ou et si non pourquoi ?

NON : 

- Pour quelle raison ? Ou habite tu ? 
- As tu peur de sauter le pas ? Raison économique ? etc ?
- Quel sont tes peurs administratives ?
- Dans le cas ou tu n'a pas les informations nécessaire ou rechercherai tu ces information ? Proche ? Internet ? Livre ? Agence ? Etc.


- Passerai tu par une application qui t’accompagnerai à crée ton dossier ?
- Virtualises tu tes documents ? Si oui comment ? Si non pourquoi ?
- Utilises-tu des plateforme comme dropbox, google drive pour stocker des documents perso ? Si oui que te manquerai t'il sur ces plateforme ? Si non pourquoi ?
- Es tu familier avec les démarches administratives en tout genre ? 
si oui quels ont été les problèmes que tu as rencontré ? Si non quelle sont tes appréhensions ?

**Comment by Akecel** [comment]
@lacaux-gerome  
 Je sais pas si tu avais revu les ordres mais en tout cas c'était dans le bon ordre, j'ai revu un peu la forme mais sinon ca me parait bien

**Comment by lacaux-gerome** [comment]
Je comprends pas le fais de trier el parcours suivant si on est étudiant ou non :/

**Comment by lacaux-gerome** [comment]
### Premier retour : 
**Le cas interrogé  :** 
Passé par une agence - pas de contact avec le proprio - problème de timing 
**Peurs** :
Le faire tout seul - dossier relou à faire - salaire élevé s 
**Tu as impliqué tes parents ?**
 Oui car ils payaient, pour la signature etc… parent pas sur Paris du coup compliqué pour signer. 
**Galère pour réunir tes papiers ?** 
Pas trop les parents s’en sont occupé.
Gardes tu les papiers à un endroit précis ? 
Tout les papiers chez elle
**Vitualise tu tes papiers** ?
Non sauf ce qui est déjà numérique et inversement si c’est en pdf elle le laisse sous ce format
Elle utilise google drive pour stocker une partie des documents
**Passerai tu par une application qui t’accompagnerai à crée ton dossier ?**
Oui pourquoi pas mais il faut avoir des garantis de sécurité
**Es tu familière avec les démarches ?** 
Aussi peu que possible mais oui quand même.

### Soucis : 
Problème avec les impôts. Manque de suivi et non sens administratif. Mail via l’intranet plus une lettre recommandé. Suivi des étapes inexistant. Lenteur.

**Comment by JessicaThi** [comment]
Rabie
21 ans 
Etudiant (alternant)

**Impression globale sur la facilité de trouver un bien ?   Impression globale sur le process - les documents nécessaire**
A Paris c’est dur de trouver des logements mais ailleurs ça va.

Rabie a déjà eu plusieurs logements dans plusieurs villes/régions différentes :

- **Saint-Die-Des-Vosges** (l’est de France) c’était chez un particulier, le logement a été trouvé quand Rabie était encore au Maroc. Il avait trouvé le logement sur LeBonCoin. Le proprio lui a demandé s’il avait un garant en France et le garant à donner la caution.

- **Nancy** : Il a cherché pendant 1 mois, 15 visites chez des particuliers. Il voulait aller chez un particulier car il aime pas trop où il y a beaucoup de gens. Aussi, sa famille vient souvent chez lui ce qui n’est pas possible dans une résidence étudiante.  Idem, il a demandé s’il avait un garant en Europe mais à ce moment là il avait **plus de garant**. Le proprio l’a accepté car le proprio a appelé l’ancien proprio pour savoir si Rabie était quelqu’un de fiable et recommandable. Donc Rabie a dû payer 2 mois cash le montant du loyer.  Et au bout de 2 mois il payait par virement. 

- **Paris** : il a postulé pour le Crous et d’autres endroits et n’a jamais été accepté car il n’avait de pas garant en Europe. Il devait trouver un logement pour son stage de fin d’étude.  Plus tard, en faisant des recherches il est tombé sur le logement étudiants « Ecla » à Massy. Il les a contacté par tel et a expliqué sa situation en disant qu’il n'a pas de garant en Europe mais qu’il a un contrat pro, il pourra toujours contacté ses parents en cas de problème. Il a dû donné 2 mois de caution. 


**==>** Les deux premiers logements, le processus des papiers étaient facile parce qu’il avait juste le bail a signé, la carte d’identité, les cartes d’identités des parents.  
Ecla : A l’h actuelle ils n’ont toujours rien demander pour les papiers. Juste un assurance d’habitation.

**Quel était le plus gros problème pour réunir tes papier ?**
Donc il n’a pas vraiment eu de difficultés pour les papiers (à voir dans les réponses précédentes)

**As-tu déjà cherché sur internet comment faire son dossier ?**
Il n’a jamais fait des recherches pour connaitre quels papiers fournir pour le dossier. Il demande directement au proprio. 

**Gardes-tu tes papiers au même endroit ?**
Il garde ses papiers importants dans un classeur (ex: contrats, banque, assurance,...).

**Passerai tu par une application qui t’accompagnerai à crée ton dossier ?**
Il utiliserait cette application uniquement si elle l’aide à trouver des logements. 

**Virtualises tu tes documents ? - > Comment ?**
Oui et non. Par exemple pour le logement Ecla il a scanné ses papiers et envoyé par mail car il ne pouvait pas donné ses papiers sur place. Il les a scanné avec CamScanner avec son téléphone. Il garde toujours une copie sur son téléphone pour être à l’abri de toutes les situations.

**Utilises-tu des plateforme comme dropbox, google drive pour stocker des documents perso ?**
Il stocke ses papiers sur Google drive car il y a plus d’espaces et c’est intégré par défaut sur Android. Il utilise aussi Dropbox mais moins qu’avant à cause de la capacité du stockage. 

**Es tu familier avec les démarches administratives ? (n'importe quel démarche)**
Oui mais en France c’est pas très clair car ça dépend de la région où tu es. Chaque région traite les démarches différemment et pas à la même fréquence. 

**Quels ont été les problèmes que tu as rencontré ?**
Oui il a rencontré des problèmes sur Paris car il a commencé les démarches sur Nancy pour sa carte de séjour. Ça a pris beaucoup de temps et entre temps il a déménagé à Paris. Et quand il a récupéré sa carte de séjour à Nancy.. Il ne sait pas s'il doit refaire les démarches pour Paris…

**Comment by JessicaThi** [comment]
Guillaume
25 ans 
Etudiant (alternant  )

**Impression globale sur la facilité de trouver un bien ?   Impression globale sur le process - les documents nécessaire**

- **Paris** : c’est pas facile de trouver un logement et encore moins quand on peut pas visiter (il habitait dans le sud quand il cherchait un logement à Paris). En plus, les loyers sont élevés et il y a pas beaucoup d’annonces. Il a trouvé son logement avec une agence et l’agence lui a dit les papiers qu’il faut fournir. 


- **Aix-en-Provence** : plus facile à trouver parce que les loyers étaient moins élevés, il a pu visiter car il habitait à Marseille. Il a trouvé son logement de bouche-à-oreille. 
Papiers : ID, avis d’imposition, fiche de salaire(alternance), RIB,….

**Quel était le plus gros problème pour réunir tes papier ?**
Il est bordélique mais il s'en ait sorti parce que c'était pas des papiers trop compliqués. 

**Gardes-tu tes papiers au même endroit ?**
Maintenant oui, il un classeur où il mets tous ses papiers, fiche de salaire, factures, diplôme ,… 

**Passerai tu par une application qui t’accompagnerai à crée ton dossier ?**
Oui pour l’app, comme ça il garde son dossier. C’est plus simple à gérer, pas de risque de perte de papiers

**Virtualises tu tes documents ? - > Comment ?**
Maintenant oui, il a tout scanné et il mets tout sur google drive. Il utilise une imprimante pour scanner. 

**Es tu familier avec les démarches administratives ? (n'importe quel démarche)**
Les démarches pour lui sont pas compliqué mais chiante. 

**Quels ont été les problèmes que tu as rencontré ?**
Perte de papier qu’il a dû redemander à la commune, la mairie, l’école

**Comment by lacaux-gerome** [comment]
**Debrief des interview 1er jet :** https://docs.google.com/document/d/1GBag44nMJnLdDPFYFvUW9X9lqt5Dz-QFYLFgLisp1Xo/edit

**Comment by lacaux-gerome** [comment]
Comment avez-vous défini le besoin auquel répond Shine ?

Avez-vous effectué des recherches en interrogeant vos cibles et/ou usagers ? Si oui quelle était votre stratégie ?

Combien de persona avez-vous défini ?

Pourquoi avez vous choisi une application et non un site internet classique ? 

Pour votre nouvelle feature les "relevés bancaires" comment avez-vous recueilli le besoin et comment l'avez-vous traduite en une solution technique ?

**Comment by JessicaThi** [comment]
**Questionnaire Shine :**

**Questions de Gérome :**
**Comment avez-vous défini le besoin auquel répond Shine ?**
https://www.frenchweb.fr/fw-radar-shine-lapplication-bancaire-pour-les-independants/327490

**Avez-vous effectué des recherches en interrogeant vos cibles et/ou usagers ? Si oui quelle était votre stratégie ?**
—> Les cibles sont les indépendants

**Avez-vous défini des personas ? Si oui, combien?**

**Pourquoi avez-vous choisi une application ?**

**(Pour votre nouvelle feature les "relevés bancaires" comment avez-vous recueilli le besoin ? Comment l'avez-vous traduite en une solution technique ?)** --> c'est un classique pour les banques


**Question de Jessica :**
**Comment avez-vous défini Shine à vos débuts ?** (+ pour aider les auto-entrepreneurs dans les démarches administratives ? + une banque pour les auto-entrepreneurs ? /// + plateforme de service ou + banque)
—> plus une plateforme de service à ses débuts

**Avez-vous contacté des spécialistes ( « juridique », financier, administratif, banquier, …) pour lancer votre concept ?**

**Quel est votre « business model » ? A-t-il évolué depuis votre lancement ?**

**(Quelle seraient vos axes d’amélioration ?)**
—> Répondu dans l’interview écrit aussi

**Est-ce que vos ambitions ont changé depuis vos débuts ?**
Ils veulent toujours simplifié et aidé les démarches administratives pour les indépendants (idem ils y répondent dans l’interview écrit)

**Résumé :**
une majorité des questions sont répondu dans ces deux interviews
https://wydden.com/nicolas-reboud-ceo-de-shine-mon-moteur-pour-entreprendre-cest-lexcitation-de-construire-quelque-chose-de-zero/
https://soundcloud.com/wydden/nicolas-reboud-mon-moteur-pour-entreprendre
