### ISSUE TITLE
Interview Shine

### ISSUE THREAD

**Issue by monacalibani** [DeathCoinOfTheDoom/h2w#21]
- [x] Préparer l'interview pour l'entretient avec l'équipe

**Comment by lacaux-gerome** [comment]
### Interview Shine 1er jet :
Comment avez-vous défini le besoin auquel répond Shine ?

Pourquoi avez vous choisi une application et non un site internet classique ?

Avez-vous effectué des recherches en interrogeant vos cibles et/ou usagers ? Si oui quelle était votre stratégie ?

Combien de persona avez-vous défini ?

Pour votre nouvelle feature les "relevés bancaires" comment avez-vous recueilli le besoin et comment l'avez-vous traduite en une solution technique ?

Avez-vous contacté des spécialistes ( « juridique », financier, administratif, banquier, …) pour lancer votre concept ? 

Quel est votre « business model » ?

A-t-il évolué depuis votre lancement ?

Quels étaient les autres models envisagé ? 

@monacalibani @AKaouthar @Akecel J'ai fais un mix des questions de Jessica et de moi. Je vous laisse jeter un oeil

**Comment by lacaux-gerome** [comment]
Commentaire de @JessicaThi 

Questionnaire Shine :

Questions de Gérome :
Comment avez-vous défini le besoin auquel répond Shine ?
https://www.frenchweb.fr/fw-radar-shine-lapplication-bancaire-pour-les-independants/327490

Avez-vous effectué des recherches en interrogeant vos cibles et/ou usagers ? Si oui quelle était votre stratégie ?
—> Les cibles sont les indépendants

Avez-vous défini des personas ? Si oui, combien?

Pourquoi avez-vous choisi une application ?

(Pour votre nouvelle feature les "relevés bancaires" comment avez-vous recueilli le besoin ? Comment l'avez-vous traduite en une solution technique ?) --> c'est un classique pour les banques

Question de Jessica :
Comment avez-vous défini Shine à vos débuts ? (+ pour aider les auto-entrepreneurs dans les démarches administratives ? + une banque pour les auto-entrepreneurs ? /// + plateforme de service ou + banque)
—> plus une plateforme de service à ses débuts

Avez-vous contacté des spécialistes ( « juridique », financier, administratif, banquier, …) pour lancer votre concept ?

Quel est votre « business model » ? A-t-il évolué depuis votre lancement ?

(Quelle seraient vos axes d’amélioration ?)
—> Répondu dans l’interview écrit aussi

Est-ce que vos ambitions ont changé depuis vos débuts ?
Ils veulent toujours simplifié et aidé les démarches administratives pour les indépendants (idem ils y répondent dans l’interview écrit)

Résumé :
une majorité des questions sont répondu dans ces deux interviews
https://wydden.com/nicolas-reboud-ceo-de-shine-mon-moteur-pour-entreprendre-cest-lexcitation-de-construire-quelque-chose-de-zero/
https://soundcloud.com/wydden/nicolas-reboud-mon-moteur-pour-entreprendre

**Comment by lacaux-gerome** [comment]
@JessicaThi je te rejoins pas totalement. Nos question vont plus interroger leurs méthodes. La réponse que l'on recherche n'est pas quel est leur cible. Mais comment ont-ils trouver ces cibles. On cherche à analyser leur méthodes et non leur réponses. 
Quand tu monte une boite qui lève 8millions je pense que tu fais des recherches pour savoir pourquoi une application mobile.
