### ISSUE TITLE
Interview physique étudiants 26/11/2018

### ISSUE THREAD

**Issue by monacalibani** [DeathCoinOfTheDoom/h2w#23]
Interroger des étudiants

**Comment by AKaouthar** [comment]
Yasmine
24 ans
Etudiante (En recherche d'alternance  )

**Impression globale sur la facilité de trouver un bien ?   Impression globale sur le process - les documents nécessaire**

**Paris** : c'est compliqué de trouver un appartement, les prix sont assez élevés et il y a beaucoup de demande. C'est aussi compliqué d'avoir une visite.
Il demandent beaucoup de documents qui parfois prennent du temps a être délivré.

**Nice** : plus d'offres moins de demandes, les prix sont moins élevés, moins stricte sur les dossiers. Les agents immobiliers sont plus cool.

**Quel était le plus gros problème pour réunir tes papier ?**
Les documents parfois demandés n'existe pas dans le pays ou mes parents habitent. C'est compliqué d'avoir des originaux quand il faut aller les chercher dans un autre pays.

**Gardes-tu tes papiers au même endroit ?**
Oui sur mon ordi, iCloud pour mon telephone et support papier (dans un classeur).

**Passerai tu par une application qui t’accompagnerai à crée ton dossier ?**
Oui mais j'ai peur de mettre ma carte d'identité dessus par exemple, peur des usurpations d'identités etc...

**Virtualises tu tes documents ? - > Comment ?**
Oui tout sur mon ordi et mon telephone (iCloud) 

**Es tu familier avec les démarches administratives ? (n'importe quel démarche)**
Oui.

**Quels ont été les problèmes que tu as rencontré ?**
J’envoie des demandes personne ne me répond, j’appelle on me dit vous préparez le dossier mais plus rien après.

**Comment by lacaux-gerome** [comment]
Premier retour :
Le cas interrogé :
Passé par une agence - pas de contact avec le proprio - problème de timing
Peurs :
Le faire tout seul - dossier relou à faire - salaire élevé s
Tu as impliqué tes parents ?
Oui car ils payaient, pour la signature etc… parent pas sur Paris du coup compliqué pour signer.
Galère pour réunir tes papiers ?
Pas trop les parents s’en sont occupé.
Gardes tu les papiers à un endroit précis ?
Tout les papiers chez elle
Vitualise tu tes papiers ?
Non sauf ce qui est déjà numérique et inversement si c’est en pdf elle le laisse sous ce format
Elle utilise google drive pour stocker une partie des documents
Passerai tu par une application qui t’accompagnerai à crée ton dossier ?
Oui pourquoi pas mais il faut avoir des garantis de sécurité
Es tu familière avec les démarches ?
Aussi peu que possible mais oui quand même.

Soucis :
Problème avec les impôts. Manque de suivi et non sens administratif. Mail via l’intranet plus une lettre recommandé. Suivi des étapes inexistant. Lenteur.

**Comment by lacaux-gerome** [comment]
cf issue #18
