### ISSUE TITLE
Userflow final 22/11/18

### ISSUE THREAD

**Issue by lacaux-gerome** [DeathCoinOfTheDoom/h2w#27]

**Comment by AKaouthar** [comment]
![img_6832](https://user-images.githubusercontent.com/18102436/49588420-ea702a80-f966-11e8-9e66-ad59f0868850.JPG)

**Comment by Akecel** [comment]
![userflow](https://user-images.githubusercontent.com/32711265/49588551-4a66d100-f967-11e8-9b9a-2bebfcbad6f6.jpg)
