### ISSUE TITLE
Proposez un slogan pour accompagner le nom de l’appli

### ISSUE THREAD

**Issue by lacaux-gerome** [DeathCoinOfTheDoom/h2w#4]
ex: « Un Job en  minutes » > a ne pas reprendre

**Comment by Akecel** [comment]
Hyra Slogan : 

Une location ? Soyez tranquille, on s'en occupe.

@lacaux-gerome  ?

**Comment by Akecel** [comment]
Une location ? Soyez tranquille, on vous accompagne.
