### ISSUE TITLE
UI/ Illustration onboarding • 25/03

### ISSUE THREAD

**Issue by Akecel** [DeathCoinOfTheDoom/h2w#48]
- [x] Bob le portefeuille sécurisé de vos documents

- [x] Bob vous guide et accompagne
Expliquez les catégories (Ajoutez vos documents...)

- [x] Expliquez la creation de dossier (En quelques cliques Bob vous guide afin de créer votre dossier...)

- [x] Envoi du dossier (Envoyez vos dossiers simplement)
 
- [x] Commencez maintenant

- [x] Un modèle intégrer dans l'écran d'accueil

**Comment by Akecel** [comment]
• Bob est un portefeuille sécurisé pour stocker tous les document lié à vos demande de locations.

• Bob vous guide et vous accompagne lors la constitutions de vos dossier locatifs, plus question d’oublier un document !

• Afin de vous organiser au mieux, plusieures catégories sont à votre dispositions pour stocker vos documents par thème.

• Constituez ensuite des dossiers personnalisés, nommez les comme bon vous semble et intégrez-y les documents que vous souhaitez.

• Enfin, d’un simple geste, envoyez votre dossier au propriétaire avec tous vos document et ainsi, démarquer vous des autres candidats

• Alors ? Convaincu ? C’est partie

**Comment by AKaouthar** [comment]
Bob est un portefeuille sécurisé ayant pour rôle de stocker tous les document lié à vos demande de locations.
**—> Le chien bob avec un dossier sous le bras**

Bob vous guide et vous accompagne lors la constitutions de vos dossier locatifs, plus question d’oublier un document !
**—> Bob au milieu avec des documents autour de lui ( genre gros bordel de documents)  ou alors avec une carte dans la main pour faire guide**

Afin de vous organiser au mieux, plusieurs sections sont à votre dispositions pour stocker vos documents par catégories.
**—>Bob devant un wireframes de liste des catégories**  

Constituez ensuite vos dossiers locatif, personnalisez les et choisissez les documents que vous souhaitez y intégrer.
**—> Bob entouré de ses documents bien rangés (dans des pochettes de couleurs (comme nos catégories)**

Enfin, d’un simple geste, envoyez votre dossier au propriétaire avec tous vos document et ainsi, démarquez vous des autres candidats.
**—> Bob avec le dossier qui s’envole vers un autre bob** 

On y va ? C’est parti !
**Bob qui fait un 😉**
