### ISSUE TITLE
Faire une page Facebook pour le projet

### ISSUE THREAD

**Issue by lacaux-gerome** [DeathCoinOfTheDoom/h2w#5]
- [x] Description de page rédigée, cover (photomontage avec  illustration ou texte), image de profil (logo). 

- [x] Concevez et intégrez 8 posts avec, pour chacun :
Une accroche originale donnant envie de télécharger l’application 
Un texte explicatif, pertinent et attractif, d’au moins 500 caractères 
Un photomontage ou une illustration (de votre création), ou une video
Un lien de lead (mettez un lien bidon)

> Insérez l’url de la page dans le dossier, ainsi que des copies écran de la page et des posts.

- [x] Proposez un modèle de planning de publication hebdomadaire en expliquant le nombre de publications par semaine que vous recommandez, les jours et les heures de publication.

**Comment by Akecel** [comment]
Hyra, une application mobile destinée aux locataires comme aux loueurs pour leur simplifier les procédures, de l'annonce jusqu'à la remise des clefs.
@lacaux-gerome  Validation de la description ?
